model_type: hand
path_ext: ./models/hand/
scene_path: ./models/hand/scene.xml
param_path: ./models/hand
param_file: parameters_init.yaml
param_data_gen_file: parameters_data_gen.yaml
crit_speed: 100
max_episode_len: 500
ft_input_len: 6
freq: 100
apply_ft_body_id: 3
lam_reward: 1
data_path: data_hand