model_type: knee
path_ext: ./models/knee/  # use 'knee' or 'knee_pos' (with position + springlength)
scene_path: ./models/knee/scene.xml
param_path: ./models/knee
param_file: parameters_init.yaml
param_data_gen_file: parameters_data_gen.yaml
crit_speed: 100
max_episode_len: 500
ft_input_len: 6
freq: 100
apply_ft_body_id: 3
lam_reward: 20
data_path: data_knee_random